// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1sfHfmKRZoi1ObxlMcddlZ0abMzBfWU0',
    appId: '1:924835253163:web:c5f4c7b5ddd34f6c9320ee',
    messagingSenderId: '924835253163',
    projectId: 'djsports-3c714',
    authDomain: 'djsports-3c714.firebaseapp.com',
    storageBucket: 'djsports-3c714.appspot.com',
    measurementId: 'G-FKSQ5PNBLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1aIEas-VzKHoRUvPDq_j2_8wT7OjCWrs',
    appId: '1:924835253163:android:1253893e882e28e59320ee',
    messagingSenderId: '924835253163',
    projectId: 'djsports-3c714',
    storageBucket: 'djsports-3c714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQppcgw8IFTvMCT805MHohrs40iVizPHE',
    appId: '1:924835253163:ios:2469006cbdcb45ce9320ee',
    messagingSenderId: '924835253163',
    projectId: 'djsports-3c714',
    storageBucket: 'djsports-3c714.appspot.com',
    iosClientId: '924835253163-9runjpvt5noccn884hv34rsbpanctpo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.djsports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQppcgw8IFTvMCT805MHohrs40iVizPHE',
    appId: '1:924835253163:ios:287c3919dc8356c99320ee',
    messagingSenderId: '924835253163',
    projectId: 'djsports-3c714',
    storageBucket: 'djsports-3c714.appspot.com',
    iosClientId: '924835253163-kup0ipr4o52o4osn0cn57pu85glvev8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.djsports.RunnerTests',
  );
}
