// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:djsports/data/models/djplaylist_model.dart';
import 'package:djsports/data/models/djtrack_model.dart';
import 'package:djsports/data/models/track_time_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DJPlaylistAdapter());
    registerAdapter(DJTrackAdapter());
    registerAdapter(TrackTimeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DJPlaylistAdapter());
    registerAdapter(DJTrackAdapter());
    registerAdapter(TrackTimeAdapter());
  }
}
